import { neon } from '@neondatabase/serverless'

const DATABASE_URL = process.env.DATABASE_URL || ''
const slugify = (value: string) =>
  value.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")

// Cocktail data from Victor's Cocktail Bible PDF
const cocktails = [
  {
    name: 'AMERICANO',
    category: 'REGULAR' as const,
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Orange slice',
    serve_extras: 'Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Campari', ml: 2.5 },
      { ingredient: 'Sweet vermouth', ml: 2.5 },
    ],
  },
  {
    name: 'APEROL SPRITZ',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Red wine',
    straining: null,
    garnish: 'Orange slice',
    serve_extras: 'Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Aperol', ml: 5.5 },
      { ingredient: 'Prosecco', ml: 9 },
    ],
  },
  {
    name: 'BRANDY ALEXANDER',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Sugar rim',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 4.5 },
      { ingredient: 'Creme de cacao', ml: 1.5 },
      { ingredient: 'Cream', ml: 40 },
      { ingredient: 'Syrup', ml: 5 },
    ],
  },
  {
    name: 'AVIATION',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 4.5 },
      { ingredient: 'Maraschino', ml: 1.5 },
      { ingredient: 'Creme de violette', ml: 2 },
      { ingredient: 'Lemon juice', ml: 2 },
    ],
  },
  {
    name: 'AIR MAIL',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: null,
    serve_extras: 'Top w/ Champagne',
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 3.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Honey syrup', ml: 1 },
    ],
  },
  {
    name: "BEE'S KNEES",
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Honey syrup', ml: 1.5 },
    ],
  },
  {
    name: 'BETWEEN THE SHEETS',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Orange twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Light rum', ml: 2.5 },
      { ingredient: 'Cognac', ml: 2.5 },
      { ingredient: 'Triple sec', ml: 2.5 },
      { ingredient: 'Lemon juice', ml: 2 },
    ],
  },
  {
    name: 'BLACK RUSSIAN',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Lowball',
    straining: null,
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3 },
      { ingredient: 'Kahlua', ml: 3 },
    ],
  },
  {
    name: 'BELLINI',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Champagne',
    straining: null,
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Prosecco', ml: 12 },
      { ingredient: 'Peach puré', ml: 3.5 },
    ],
  },
  {
    name: 'BOULEVARDIER',
    category: 'REGULAR',
    technique: 'Stir w/ ice and single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Orange peel',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 2.5 },
      { ingredient: 'Campari', ml: 2.5 },
      { ingredient: 'Sweet vermouth', ml: 2.5 },
    ],
  },
  {
    name: 'BLOODY MARY',
    category: 'REGULAR',
    technique: 'Thrown w/ ice & single strain',
    glassware: 'Highball',
    straining: 'Single strain',
    garnish: 'Celery stick',
    serve_extras: '3-4 dash Tabasco, 1-2 dash Worcestershire sauce, 2-3 spins black pepper, 1 pinch celery salt',
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2 },
      { ingredient: 'Tomato juice', ml: 12 },
    ],
  },
  {
    name: 'BIJOU',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Green Chartreuse', ml: 2.5 },
      { ingredient: 'Gin', ml: 2.5 },
      { ingredient: 'Sweet vermouth', ml: 2.5 },
    ],
  },
  {
    name: 'BRAMBLE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lemon slice',
    serve_extras: 'Top w/ soda, Bleed w/ blackberry syrup',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Simple syrup', ml: 1 },
    ],
  },
  {
    name: 'BRANDY CRUSTA',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Snifter',
    straining: 'Double strain',
    garnish: 'Sugar rim and orange peel',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Maraschino', ml: 0.5 },
      { ingredient: 'Lemon juice', ml: 2 },
      { ingredient: 'Syrup', ml: 5 },
    ],
  },
  {
    name: 'BOBBY BURNS',
    category: 'REGULAR',
    technique: 'Stir w/ ice and single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Orange twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Scotch whiskey', ml: 4.5 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
      { ingredient: 'D.O.M benedictine', ml: 5 },
      { ingredient: 'Angostura bitters', ml: 1.5 },
    ],
  },
  {
    name: 'CHARLIE CHAPLIN',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Lime zest',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Sloe Gin', ml: 3.5 },
      { ingredient: 'Apricot brandy', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'CAIPIRINHA',
    category: 'REGULAR',
    technique: 'Muddle & built',
    glassware: 'Lowball',
    straining: null,
    garnish: 'Lime wedge',
    serve_extras: '2 tbsp Brown sugar, 4 lime wedges',
    is_batched: false,
    ingredients: [
      { ingredient: 'Cachaca', ml: 5 },
      { ingredient: 'Lime juice', ml: 1 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'CAPRINOWSKA',
    category: 'REGULAR',
    technique: 'Muddled & Built',
    glassware: 'Lowball',
    straining: null,
    garnish: 'Lime wedge',
    serve_extras: '2 tbsp Brown sugar, 4 lime wedges',
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 5 },
      { ingredient: 'Lime juice', ml: 1 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'CHAMPAGNE COCKTAIL',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Champagne',
    straining: null,
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 3 },
      { ingredient: 'Syrup', ml: 5 },
      { ingredient: 'Champagne', ml: 12 },
      { ingredient: 'Angostura bitters', ml: 1.5 },
    ],
  },
  {
    name: 'CLOVER CLUB',
    category: 'REGULAR',
    technique: 'Dry shake, w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: '3 Raspberries on a stick',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 4.5 },
      { ingredient: 'Dry vermouth', ml: 0.5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Raspberry syrup', ml: 2 },
      { ingredient: 'Egg white', ml: 3.5 },
    ],
  },
  {
    name: 'CORPSE REVIVER NO.2',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: '1 spray absinthe',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 2.5 },
      { ingredient: 'Lillet blanc', ml: 2.5 },
      { ingredient: 'Triple sec', ml: 2.5 },
      { ingredient: 'Lemon juice', ml: 20 },
    ],
  },
  {
    name: 'COSMOPOLITAN',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Orange zest & dried lime',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Cranberry juice', ml: 5 },
      { ingredient: 'Syrup', ml: 5 },
    ],
  },
  {
    name: 'DEATH IN THE AFTERNOON',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Champagne',
    straining: null,
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Prosecco', ml: 50 },
      { ingredient: 'Absinthe', ml: 50 },
    ],
  },
  {
    name: 'DAIQUIRI',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Light rum', ml: 5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 2 },
    ],
  },
  {
    name: 'DARK & STORMY',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lime wedge',
    serve_extras: 'Top w/ Ginger beer',
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 5 },
      { ingredient: 'Angostura bitters', ml: 2 },
    ],
  },
  {
    name: 'DRY MARTINI',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: '3 olives or lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 6 },
      { ingredient: 'Dry vermouth', ml: 5 },
      { ingredient: 'Orange bitters', ml: 1 },
    ],
  },
  {
    name: 'DIRTY MARTINI',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: '3 olives',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 6 },
      { ingredient: 'Dry vermouth', ml: 5 },
      { ingredient: 'Olive brine', ml: 5 },
    ],
  },
  {
    name: 'EAST SIDE',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Mint leaf',
    serve_extras: 'Cucumber slices, Mint leaves',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 2 },
    ],
  },
  {
    name: 'ESPRESSO MARTINI',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: '3 espresso beans',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 4 },
      { ingredient: 'Kahlua', ml: 1.5 },
      { ingredient: 'Double espresso', ml: 5.5 },
      { ingredient: 'Syrup', ml: 5 },
    ],
  },
  {
    name: 'FRENCH 75',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Champagne',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: 'Top w/ Champagne',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 3.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'FRENCH MARTINI',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3.5 },
      { ingredient: 'Raspberry liquor', ml: 1.5 },
      { ingredient: 'Pineapple juice', ml: 6.5 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'FRENCH COFFEE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Coffee cocktail',
    straining: null,
    garnish: null,
    serve_extras: 'Top w/ Cream',
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 3 },
      { ingredient: 'Coffee', ml: 11 },
      { ingredient: 'Fairing sugar', ml: 5 },
    ],
  },
  {
    name: 'KAMIKAZE',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Dried lime',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'KAFFE KARLSSON',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Coffee cocktail',
    straining: null,
    garnish: null,
    serve_extras: 'Top w/ cream',
    is_batched: false,
    ingredients: [
      { ingredient: 'Triple sec', ml: 2 },
      { ingredient: "Bailey's", ml: 2 },
      { ingredient: 'Coffee', ml: 11 },
    ],
  },
  {
    name: 'GARIBALDI',
    category: 'REGULAR',
    technique: 'Dry shake and dirty dump',
    glassware: 'Highball',
    straining: null,
    garnish: 'Orange slice',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Campari', ml: 5 },
      { ingredient: 'Syrup', ml: 5 },
      { ingredient: 'Orange juice', ml: 12 },
    ],
  },
  {
    name: 'GIN BASIL SMASH',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Lowball',
    straining: 'Double strain',
    garnish: 'Basil leaf',
    serve_extras: 'Basil leaves',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'GIN FIZZ',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Highball',
    straining: 'Double strain',
    garnish: 'Lemon slice',
    serve_extras: 'Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Egg white', ml: 2.5 },
    ],
  },
  {
    name: 'GRASSHOPPER',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Nutmeg or choco powder',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Creme de menthe', ml: 2.5 },
      { ingredient: 'Creme de cacao', ml: 2.5 },
      { ingredient: 'Cream', ml: 4 },
      { ingredient: 'Syrup', ml: 5 },
    ],
  },
  {
    name: 'GOLD RUSH',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Lowball',
    straining: 'Double strain',
    garnish: 'Lemon peel',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Honey syrup', ml: 1.5 },
    ],
  },
  {
    name: 'GIMLET',
    category: 'REGULAR',
    technique: 'Shake/throw w/ ice & double/single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lime medallion',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Lime cordial', ml: 1.5 },
    ],
  },
  {
    name: 'HANKY PANKY',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lemon peel',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 3 },
      { ingredient: 'Sweet vermouth', ml: 2.5 },
      { ingredient: 'Fernet brance', ml: 1.5 },
    ],
  },
  {
    name: 'HEMINGWAY DAIQUIRI',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 5.5 },
      { ingredient: 'Maraschino', ml: 5 },
      { ingredient: 'Lime juice', ml: 1.5 },
      { ingredient: 'Grapefruit juice', ml: 3.5 },
    ],
  },
  {
    name: 'HURRICANE',
    category: 'REGULAR',
    technique: 'Shake w/ ice & dirty dump',
    glassware: 'Sling',
    straining: null,
    garnish: 'Cherry & orange slice',
    serve_extras: 'Cubed & top w/ crushed',
    is_batched: false,
    ingredients: [
      { ingredient: 'Light rum', ml: 4 },
      { ingredient: 'Dark rum', ml: 2 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Orange juice', ml: 5.5 },
      { ingredient: 'Grenadine syrup', ml: 2 },
    ],
  },
  {
    name: 'HUGO',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Red wine',
    straining: null,
    garnish: 'Lemon slice',
    serve_extras: 'Mint, Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Elderflower liquor', ml: 5 },
      { ingredient: 'Prosecco', ml: 9 },
    ],
  },
  {
    name: 'IRISH COFFEE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Café cocktail',
    straining: null,
    garnish: 'Coffee bean',
    serve_extras: 'Top w/ Cream',
    is_batched: false,
    ingredients: [
      { ingredient: 'Irish whiskey', ml: 3 },
      { ingredient: 'Farin sugar', ml: 5 },
      { ingredient: 'Coffee', ml: 9 },
    ],
  },
  {
    name: 'JUNGLE BIRD',
    category: 'REGULAR',
    technique: 'Shake w/ ice & dirty dump',
    glassware: 'Lowball',
    straining: null,
    garnish: 'Pineapple slice or Orange slice',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 4 },
      { ingredient: 'Campari', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Pineapple juice', ml: 4 },
      { ingredient: 'Syrup', ml: 2 },
    ],
  },
  {
    name: 'KIR ROYAL',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Champagne',
    straining: null,
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Creme de cassis', ml: 2.5 },
      { ingredient: 'Champagne', ml: 12 },
    ],
  },
  {
    name: 'LAST WORD',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Maraschino cherry',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 2.5 },
      { ingredient: 'Maraschino', ml: 2.5 },
      { ingredient: 'Green Chartreuse', ml: 2.5 },
      { ingredient: 'Lime juice', ml: 2.5 },
    ],
  },
  {
    name: 'LYNCBERG LEMONADE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lime',
    serve_extras: 'Top w/ Sprite or soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Tennessee whiskey', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 5 },
    ],
  },
  {
    name: 'LONG ISLAND ICE TEA',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball/Red wine/Sling',
    straining: null,
    garnish: 'Lemon slice',
    serve_extras: 'Top w/ Coca cola',
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 2 },
      { ingredient: 'Light rum', ml: 2 },
      { ingredient: 'Gin', ml: 2 },
      { ingredient: 'Tequila', ml: 2 },
      { ingredient: 'Triple sec', ml: 2 },
      { ingredient: 'Lemon juice', ml: 2 },
    ],
  },
  {
    name: 'LOST PLANE',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 2.5 },
      { ingredient: 'Aperol', ml: 2.5 },
      { ingredient: 'Amaro', ml: 2.5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
    ],
  },
  {
    name: 'LEMON DROP',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'MAI TAI',
    category: 'REGULAR',
    technique: 'Shake w/ ice & dirty dump',
    glassware: 'Lowball',
    straining: null,
    garnish: 'Orange slice & mint sprig',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Light rum', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Orange juice', ml: 4 },
      { ingredient: 'Oregat syrup', ml: 2 },
    ],
  },
  {
    name: 'MANHATTAN',
    category: 'REGULAR',
    technique: 'Stir w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Maraschino cherry on a stick',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Rye whisky', ml: 4.5 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
      { ingredient: 'Angostura bitter', ml: 2.5 },
    ],
  },
  {
    name: 'MARGARITA',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Salt rim',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Tequila', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'MARTINEZ',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Maraschino cherry',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 4 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
      { ingredient: 'Maraschino', ml: 5 },
      { ingredient: 'Angostura bitters', ml: 2.5 },
    ],
  },
  {
    name: 'MARY PICKFORD',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Maraschino on stick',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 4.5 },
      { ingredient: 'Maraschino', ml: 5 },
      { ingredient: 'Pineapple juice', ml: 4 },
      { ingredient: 'Lime juice', ml: 1 },
      { ingredient: 'Grenadine', ml: 1.5 },
    ],
  },
  {
    name: 'MIMOSA',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Champagne',
    straining: null,
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Champagne', ml: 50 },
      { ingredient: 'Orange juice', ml: 50 },
    ],
  },
  {
    name: 'MINT JULEP',
    category: 'REGULAR',
    technique: 'Built & Swizzle',
    glassware: 'Lowball or Julep cup',
    straining: null,
    garnish: 'Lemon slice & mint sprig',
    serve_extras: 'Mint',
    is_batched: false,
    ingredients: [
      { ingredient: 'Whiskey', ml: 5 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'MOJITO',
    category: 'REGULAR',
    technique: 'Built & swizzle',
    glassware: 'Highball',
    straining: null,
    garnish: 'Mint sprig & dried lime',
    serve_extras: 'Mint, Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Light rum', ml: 5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 2 },
    ],
  },
  {
    name: 'MOSCOW MULE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lime wedge',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'MEXICAN MULE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lime wedge',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Tequila', ml: 5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'MIAMI VICE',
    category: 'REGULAR',
    technique: 'Built & layered',
    glassware: 'Sling',
    straining: null,
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Frozen Pina Colada', ml: 50 },
      { ingredient: 'Frozen strawberry daiquiri', ml: 50 },
    ],
  },
  {
    name: 'NAKED & FAMOUS',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Dried lime',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Mezcal', ml: 2.5 },
      { ingredient: 'Aperol', ml: 2.5 },
      { ingredient: 'Yellow Chartreuse', ml: 2.5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
    ],
  },
  {
    name: 'NEGRONI',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Lowball',
    straining: 'Single strain',
    garnish: 'Orange slice',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 2.5 },
      { ingredient: 'Campari', ml: 2.5 },
      { ingredient: 'Sweet vermouth', ml: 2.5 },
    ],
  },
  {
    name: 'NEGRONI SPAGLIATO',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Red wine',
    straining: null,
    garnish: 'Orange slice',
    serve_extras: 'Top w/ prosecco',
    is_batched: false,
    ingredients: [
      { ingredient: 'Campari', ml: 2.5 },
      { ingredient: 'Sweet vermouth', ml: 2.5 },
    ],
  },
  {
    name: 'NEW YORK SOUR',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Lowball or Red wine',
    straining: 'Double strain',
    garnish: 'Lemon slice',
    serve_extras: 'Layer w/ Red wine',
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 4 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Egg white', ml: 3.5 },
    ],
  },
  {
    name: 'OLD CUBAN',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Mint leaf',
    serve_extras: 'Top w/ Champagne, Mint',
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 3.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'OLD FASHIONED',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Lowball',
    straining: 'Single strain',
    garnish: 'Orange zest & Maraschino on a stick',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 6 },
      { ingredient: 'Syrup', ml: 5 },
      { ingredient: 'Angostura bitters', ml: 2.5 },
    ],
  },
  {
    name: 'PALOMA',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Salt rim & grapefruit slice',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Tequila', ml: 5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'PERFECT LADY',
    category: 'REGULAR',
    technique: 'Dry shake & w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Dried lime',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 3.5 },
      { ingredient: 'Creme de peche', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Egg white', ml: 3.5 },
    ],
  },
  {
    name: 'PINK LADY',
    category: 'REGULAR',
    technique: 'Dry shake & w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Dried orange',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 4 },
      { ingredient: 'Apple jack', ml: 1 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Grenadine', ml: 1.5 },
      { ingredient: 'Egg white', ml: 3.5 },
    ],
  },
  {
    name: 'PAPER PLANE',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 2 },
      { ingredient: 'Aperol', ml: 2 },
      { ingredient: 'Amaro', ml: 2 },
      { ingredient: 'Lemon juice', ml: 2 },
    ],
  },
  {
    name: 'PENICILLIN',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Lowball or Nick & Nora',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Scotch whiskey', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Ginger juice', ml: 5 },
      { ingredient: 'Honey syrup', ml: 1.5 },
      { ingredient: 'Smoked islay whiskey', ml: 1 },
    ],
  },
  {
    name: 'PINA COLADA',
    category: 'REGULAR',
    technique: 'Shake w/ ice & dirty dump',
    glassware: 'Sling or wine glass',
    straining: null,
    garnish: 'Pineapple leaf',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Light rum', ml: 3.5 },
      { ingredient: 'Coconut liquor', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Cream', ml: 1.5 },
      { ingredient: 'Pineapple juice', ml: 10 },
    ],
  },
  {
    name: 'PEN DENNIS',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Maraschino cherry on a stick',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 3.5 },
      { ingredient: 'Creme de apricot', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Peychoud bitters', ml: 4.5 },
    ],
  },
  {
    name: 'PORNSTAR MARTINI',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Passionfruit wedge',
    serve_extras: 'Top w/ champagne or on the side',
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3.5 },
      { ingredient: 'Passoa', ml: 1.5 },
      { ingredient: 'Lime juice', ml: 2 },
      { ingredient: 'Vanilla syrup', ml: 2 },
      { ingredient: 'Passion puré', ml: 3.5 },
    ],
  },
  {
    name: "QUEEN'S PARK SWIZZLE",
    category: 'REGULAR',
    technique: 'Built & swizzle',
    glassware: 'Highball',
    straining: null,
    garnish: 'Dried lime & mint sprig',
    serve_extras: 'Mint, Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Dark rum', ml: 5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Angostura bitters', ml: 2.5 },
    ],
  },
  {
    name: 'ROB ROY',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Maraschino cherry',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Scotch whiskey', ml: 4.5 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
      { ingredient: 'Angostura bitters', ml: 1.5 },
    ],
  },
  {
    name: 'REMEMBER THE MAINE',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Lowball',
    straining: 'Single strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 2.5 },
      { ingredient: 'Rye whiskey', ml: 2 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
      { ingredient: 'Cherry heering', ml: 1 },
    ],
  },
  {
    name: 'RATTLE SNAKE',
    category: 'REGULAR',
    technique: 'Dry shake & w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: '3 dots angostura',
    serve_extras: 'Rinse w/ 1-2 spray absinthe',
    is_batched: false,
    ingredients: [
      { ingredient: 'Rye whiskey', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Egg white', ml: 3.5 },
    ],
  },
  {
    name: 'RICKEY',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lime wedge',
    serve_extras: 'Top w/ soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Spirit of choice', ml: 5 },
      { ingredient: 'Lime juice', ml: 2 },
    ],
  },
  {
    name: 'SAZERAC',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Lowball & Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lemon twist or Maraschino',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Rye whiskey', ml: 3 },
      { ingredient: 'Cognac', ml: 3 },
      { ingredient: 'Syrup', ml: 5 },
      { ingredient: 'Peychoud bitters', ml: 3.5 },
    ],
  },
  {
    name: 'SEX ON THE BEACH',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lemon juice',
    serve_extras: 'Bleed w/ grenadine',
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3.5 },
      { ingredient: 'Creme de peche', ml: 1.5 },
      { ingredient: 'Lemon juice', ml: 2 },
      { ingredient: 'Syrup', ml: 1 },
    ],
  },
  {
    name: 'SIDE CAR',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: 'Sugar rim',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'SOUTH SIDE',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Coupé or Nick & Nora',
    straining: 'Double strain',
    garnish: 'Mint leaf',
    serve_extras: 'Mint',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'SPRITZ',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Red wine',
    straining: null,
    garnish: 'Lemon/Lime/Orange slice',
    serve_extras: 'Top w/ soda',
    is_batched: false,
    ingredients: [
      { ingredient: 'Liquor', ml: 5 },
      { ingredient: 'Prosecco', ml: 10 },
    ],
  },
  {
    name: 'TEQUILA SUNRISE',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Orange slice',
    serve_extras: 'Bleed w/ Grenadine',
    is_batched: false,
    ingredients: [
      { ingredient: 'Tequila', ml: 5 },
      { ingredient: 'Orange juice', ml: 10 },
    ],
  },
  {
    name: 'TIPPERARY',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Irish whiskey', ml: 3.5 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
      { ingredient: 'Green chartreuse', ml: 1 },
    ],
  },
  {
    name: "TOMMY'S MARGARITA",
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Lowball',
    straining: 'Double strain',
    garnish: 'Dried lime',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Tequila', ml: 5 },
      { ingredient: 'Lime juice', ml: 2.5 },
      { ingredient: 'Agave syrup', ml: 1.5 },
    ],
  },
  {
    name: 'TOM COLLINS',
    category: 'REGULAR',
    technique: 'Built',
    glassware: 'Highball',
    straining: null,
    garnish: 'Lemon wedge',
    serve_extras: 'Top w/ Soda water',
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'VESPER',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Nick & Nora',
    straining: 'Double strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 3.5 },
      { ingredient: 'Vodka', ml: 1.5 },
      { ingredient: 'Lillet blanc', ml: 1 },
    ],
  },
  {
    name: "VIUEX CARRÉ",
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Lowball',
    straining: 'Single strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 2.5 },
      { ingredient: 'Rye whiskey', ml: 2.5 },
      { ingredient: 'Sweet vermouth', ml: 1 },
      { ingredient: 'D.O.M benedictine', ml: 5 },
      { ingredient: 'Peychaud bitters', ml: 2.5 },
      { ingredient: 'Angostura bitters', ml: 1 },
    ],
  },
  {
    name: 'VICTOR',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lemon or orange twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Cognac', ml: 3 },
      { ingredient: 'Gin', ml: 2 },
      { ingredient: 'Sweet vermouth', ml: 1.5 },
    ],
  },
  {
    name: 'MILANO TORINO',
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Lowball',
    straining: 'Single strain',
    garnish: 'Orange peel',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Campari', ml: 3 },
      { ingredient: 'Sweet vermouth', ml: 3 },
    ],
  },
  {
    name: 'WHITE LADY',
    category: 'REGULAR',
    technique: 'Dry shake & w/ ice & double strain',
    glassware: 'Coupé',
    straining: 'Double strain',
    garnish: null,
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 3.5 },
      { ingredient: 'Triple sec', ml: 1.5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
      { ingredient: 'Egg white', ml: 3.5 },
    ],
  },
  {
    name: 'WHITE NEGRONI',
    category: 'REGULAR',
    technique: 'Dry shake & w/ ice & double strain',
    glassware: 'Lowball',
    straining: 'Double strain',
    garnish: 'Lemon peel',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Gin', ml: 2.5 },
      { ingredient: 'Lillet blanc', ml: 2.5 },
      { ingredient: 'Dry vermouth', ml: 2.5 },
    ],
  },
  {
    name: "WIDOW'S KISS",
    category: 'REGULAR',
    technique: 'Stir w/ ice & single strain',
    glassware: 'Nick & Nora',
    straining: 'Single strain',
    garnish: 'Lemon twist',
    serve_extras: null,
    is_batched: false,
    ingredients: [
      { ingredient: 'Calvados', ml: 4.5 },
      { ingredient: 'Yellow chartreus', ml: 1.5 },
      { ingredient: 'D.O.M benedictine', ml: 5 },
      { ingredient: 'Angostura bitters', ml: 1.5 },
    ],
  },
  {
    name: 'WHISKEY SMASH',
    category: 'REGULAR',
    technique: 'Shake w/ ice & double strain',
    glassware: 'Lowball',
    straining: 'Double strain',
    garnish: 'Lemon wedge & mint sprig',
    serve_extras: 'Mint',
    is_batched: false,
    ingredients: [
      { ingredient: 'Bourbon', ml: 5 },
      { ingredient: 'Lemon juice', ml: 2.5 },
      { ingredient: 'Syrup', ml: 1.5 },
    ],
  },
  {
    name: 'WHITE RUSSIAN',
    category: 'REGULAR',
    technique: 'Built & layered',
    glassware: 'Lowball',
    straining: null,
    garnish: null,
    serve_extras: 'Layer w/ cream',
    is_batched: false,
    ingredients: [
      { ingredient: 'Vodka', ml: 3 },
      { ingredient: 'Kahlua', ml: 3 },
    ],
  },
]

async function syncCocktails() {
  if (!DATABASE_URL) {
    console.error('DATABASE_URL is required')
    process.exit(1)
  }

  const sql = neon(DATABASE_URL)

  try {
    // Get existing cocktails
    const existing = await sql`SELECT id, name FROM cocktails`
    const existingIds = new Set(existing.map((c: any) => c.id))

    console.log(`Found ${existing.length} existing cocktails`)

    let created = 0
    let updated = 0

    for (const cocktail of cocktails) {
      const id = slugify(cocktail.name)

      if (existingIds.has(id)) {
        // Cocktail exists - only update serve_extras if currently null/empty
        const result = await sql`SELECT serve_extras FROM cocktails WHERE id = ${id}`
        if (result.length > 0 && !result[0].serve_extras && cocktail.serve_extras) {
          await sql`UPDATE cocktails SET serve_extras = ${cocktail.serve_extras}, updated_at = now() WHERE id = ${id}`
          console.log(`✓ Updated ${cocktail.name} with serve_extras`)
          updated++
        }
      } else {
        // Create new cocktail
        await sql`INSERT INTO cocktails (id, name, category, technique, glassware, straining, garnish, serve_extras, is_batched, updated_at)
           VALUES (${id}, ${cocktail.name}, ${cocktail.category}, ${cocktail.technique}, ${cocktail.glassware}, ${cocktail.straining}, ${cocktail.garnish}, ${cocktail.serve_extras}, ${cocktail.is_batched}, now())`

        // Add ingredients
        for (const ingredient of cocktail.ingredients) {
          if (ingredient.ingredient.trim()) {
            await sql`INSERT INTO cocktail_specs (cocktail_id, ingredient, ml) VALUES (${id}, ${ingredient.ingredient.trim()}, ${ingredient.ml || 0})`
          }
        }

        console.log(`✓ Created ${cocktail.name}`)
        created++
      }
    }

    console.log(`\n✅ Sync complete: ${created} created, ${updated} updated`)
  } catch (error) {
    console.error('Error syncing cocktails:', error)
    process.exit(1)
  }
}

syncCocktails()
